apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

replicas:

  - name: web
    count: 3

configMapGenerator:

  - name: release-info

    literals:

      - ENVIRONMENT=prod
      - RELEASE_VERSION=1.0.0