apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

replicas:
  - name: web
    count: 1

configMapGenerator:

  - name: release-info

    literals:

      - ENVIRONMENT=dev
      - RELEASE_VERSION=1.1.0